In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
l = [1,2,3]
l

[1, 2, 3]

In [5]:
rev = np.array([[10,12,9], [15,14,17]])
rev

array([[10, 12,  9],
       [15, 14, 17]])

In [14]:
rev.shape
rev.ndim
rev[1,0]
rev.dtype
rev.nbytes
rev.itemsize
rev.size
rev.flatten()

array([10, 12,  9, 15, 14, 17])

In [15]:
q1 = np.array([
    [200, 220, 250],  # Product A
    [150, 180, 210],  # Product B
    [300, 330, 360]   # Product C
])

q2 = np.array([
    [209, 231, 259],  # Product A
    [155, 192, 222],  # Product B
    [310, 340, 375]   # Product C
])

In [16]:
q2-q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [17]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])